//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assembly
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assembly()
        {
            this.BOMtoAssemblies = new HashSet<BOMtoAssembly>();
            this.LeadTimeForAssemblies = new HashSet<LeadTimeForAssembly>();
            this.PartToCapitalAssembly_DEL = new HashSet<PartToCapitalAssembly_DEL>();
            this.PMFeeNotChargables = new HashSet<PMFeeNotChargable>();
        }
    
        public long ID { get; set; }
        public long vwProductsID { get; set; }
        public string Description { get; set; }
        public int AssemblyCategoryID { get; set; }
        public string Device { get; set; }
    
        public virtual AssemblyCategory AssemblyCategory { get; set; }
        public virtual BOMItem BOMItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOMtoAssembly> BOMtoAssemblies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadTimeForAssembly> LeadTimeForAssemblies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartToCapitalAssembly_DEL> PartToCapitalAssembly_DEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMFeeNotChargable> PMFeeNotChargables { get; set; }
    }
}
