//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOM()
        {
            this.BOMtoAssemblies = new HashSet<BOMtoAssembly>();
            this.LeadTimeForAssemblies = new HashSet<LeadTimeForAssembly>();
        }
    
        public int ID { get; set; }
        public string BOM1 { get; set; }
        public Nullable<bool> IsCustomParts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOMtoAssembly> BOMtoAssemblies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadTimeForAssembly> LeadTimeForAssemblies { get; set; }
    }
}
