//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOMItem()
        {
            this.Assemblies = new HashSet<Assembly>();
            this.BOMtoAssemblies = new HashSet<BOMtoAssembly>();
            this.PartToCapitalAssembly_DEL = new HashSet<PartToCapitalAssembly_DEL>();
        }
    
        public long RECID { get; set; }
        public string ITEMID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> SALEPRICE { get; set; }
        public string SALEUNIT { get; set; }
        public string PRODTYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assembly> Assemblies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOMtoAssembly> BOMtoAssemblies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartToCapitalAssembly_DEL> PartToCapitalAssembly_DEL { get; set; }
    }
}
