//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMTemplate
    {
        public int ID { get; set; }
        public int BOM_ID { get; set; }
        public long BOMItem_ID { get; set; }
        public decimal Price { get; set; }
        public decimal Quantity { get; set; }
        public bool IsQtyFixed { get; set; }
        public bool IsDiscountApply { get; set; }
        public decimal MaximumQty { get; set; }
        public Nullable<int> AssemblyID { get; set; }
        public bool IsInTotal { get; set; }
        public bool IsDecimalAllowed { get; set; }
        public Nullable<long> ParentBOMItemID { get; set; }
    }
}
