//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMtoAssembly
    {
        public int ID { get; set; }
        public int BOMid { get; set; }
        public long AssemblyID { get; set; }
        public long Device_ID { get; set; }
        public decimal PMPercentage { get; set; }
    
        public virtual Assembly Assembly { get; set; }
        public virtual BOM BOM { get; set; }
        public virtual BOMItem BOMItem { get; set; }
    }
}
