//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemCategory()
        {
            this.ItemSubCategories = new HashSet<ItemSubCategory>();
            this.PartToCategories = new HashSet<PartToCategory>();
            this.PMFeeNotChargable_DEL = new HashSet<PMFeeNotChargable_DEL>();
        }
    
        public long ID { get; set; }
        public string Category { get; set; }
        public Nullable<int> ItemOrder { get; set; }
    
        public virtual ItemCategory ItemCategory1 { get; set; }
        public virtual ItemCategory ItemCategory2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemSubCategory> ItemSubCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartToCategory> PartToCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMFeeNotChargable_DEL> PMFeeNotChargable_DEL { get; set; }
    }
}
