//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSubCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemSubCategory()
        {
            this.PartToCategories = new HashSet<PartToCategory>();
        }
    
        public long ItemCategory { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ItemOrder { get; set; }
    
        public virtual ItemCategory ItemCategory1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartToCategory> PartToCategories { get; set; }
    }
}
