//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMilestone
    {
        public int ID { get; set; }
        public int OpportunityID { get; set; }
        public int BOMID { get; set; }
        public decimal DepositPerc { get; set; }
        public decimal Deposit { get; set; }
        public decimal PreDeliveryPerc { get; set; }
        public decimal PreDelivery { get; set; }
        public decimal FinalPerc { get; set; }
        public decimal Final { get; set; }
    }
}
