//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrntHD_Consmbl_Relations
    {
        public int Relationid { get; set; }
        public string PrintHeadID { get; set; }
        public string PrintHeadDesc { get; set; }
        public string ConsummableID { get; set; }
        public string ConsummableDesc { get; set; }
    }
}
